export const LECTURES = [
  {
    subject: "BIOLOGY",
    name: "Cell division — mitosis vs meiosis",
    pct: 64,
    dur: "38 min",
    grad: "linear-gradient(135deg,#2952E3,#4E6EF2)",
    meta: "64% watched",
  },
  {
    subject: "PHYSICS",
    name: "Newton's laws — worked examples",
    pct: 30,
    dur: "44 min",
    grad: "linear-gradient(135deg,#FF7A45,#FFA26B)",
    meta: "30% watched",
  },
  {
    subject: "MATH",
    name: "Quadratic equations — full review",
    pct: 100,
    dur: "52 min",
    grad: "linear-gradient(135deg,#1F9D63,#3FBE85)",
    meta: "Completed",
  },
  {
    subject: "BIOLOGY",
    name: "Photosynthesis in depth",
    pct: 0,
    dur: "41 min",
    grad: "linear-gradient(135deg,#2952E3,#4E6EF2)",
    meta: "Not started",
  },
  {
    subject: "PHYSICS",
    name: "Energy & work — problem set",
    pct: 0,
    dur: "36 min",
    grad: "linear-gradient(135deg,#FF7A45,#FFA26B)",
    meta: "Not started",
  },
  {
    subject: "MATH",
    name: "Functions and graphs",
    pct: 12,
    dur: "29 min",
    grad: "linear-gradient(135deg,#1F9D63,#3FBE85)",
    meta: "12% watched",
  },
];
